---
- name: Check if site is already installed.
  command: >
    {{ drush_path }} status bootstrap
    chdir={{ beet_web }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false

- name: Install Drupal with drush.
  command: >
    {{ drush_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ beet_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ beet_mysql_user }}:{{ beet_mysql_password }}@{{ beet_mysql_server }}/{{ beet_mysql_database }}
    chdir={{ beet_web }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"

- name: Install configured modules with drush.
  command: >
    {{ drush_path }} pm-enable -y {{ drupal_enable_modules | join(" ") }}
    chdir={{ beet_web }}
  when: "'Successful' not in drupal_site_installed.stdout"
